"""
report_generator.py — Incident Report PDF Generator for SIH26162
================================================================
Generates a clean, professional single-page incident report PDF using ReportLab.
Contents:
  - Header: "SIH26162 — Fire Detection Incident Report"
  - Event details: timestamp, class, confidence (as %), severity
  - Snapshot image embedded (if provided and exists on disk)
  - Footer: "Generated by SIH26162 AI Detection System — prototype, not a certified safety system"
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_incident_report(
    event: dict,
    output_pdf_path: str,
    snapshot_image_path: str | None = None,
) -> str | None:
    """
    Generate a 1-page PDF incident report for a fire/smoke detection event.

    Parameters
    ----------
    event : dict
        Dict containing at least: timestamp, class, confidence, severity.
    output_pdf_path : str
        Target destination path for the generated PDF.
    snapshot_image_path : str, optional
        Path to an annotated snapshot JPEG/PNG image, if available.

    Returns
    -------
    str | None
        output_pdf_path on success, or None on failure.
    """
    try:
        os.makedirs(os.path.dirname(os.path.abspath(output_pdf_path)), exist_ok=True)

        # 0.5 inch margins (36 pt) to easily fit on a single page
        doc = SimpleDocTemplate(
            output_pdf_path,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=36,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#b71c1c"),  # Industrial alert red
            alignment=0,  # Left aligned
            spaceAfter=4,
        )

        subtitle_style = ParagraphStyle(
            "ReportSubtitle",
            parent=styles["Normal"],
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#555555"),
            spaceAfter=12,
        )

        cell_label_style = ParagraphStyle(
            "CellLabel",
            parent=styles["Normal"],
            fontSize=10,
            leading=12,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#222222"),
        )

        cell_value_style = ParagraphStyle(
            "CellValue",
            parent=styles["Normal"],
            fontSize=10,
            leading=12,
            textColor=colors.HexColor("#111111"),
        )

        footer_style = ParagraphStyle(
            "ReportFooter",
            parent=styles["Normal"],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#777777"),
            alignment=1,  # Centred
        )

        elements = []

        # 1. Header & Subtitle
        elements.append(Paragraph("SIH26162 — Fire Detection Incident Report", title_style))
        elements.append(Paragraph("Automated Critical Event Report & Evidence Capture", subtitle_style))
        elements.append(Spacer(1, 6))

        # 2. Event details
        timestamp = str(event.get("timestamp", "N/A"))
        detection_class = str(event.get("class", "N/A")).upper()
        severity = str(event.get("severity", "N/A")).upper()
        try:
            conf_val = float(event.get("confidence", 0.0)) * 100
            confidence_str = f"{conf_val:.1f}%"
        except (ValueError, TypeError):
            confidence_str = str(event.get("confidence", "N/A"))

        # Severity display colour styling
        sev_color = colors.HexColor("#b71c1c") if severity == "HIGH" else colors.HexColor("#e65100")
        sev_cell_style = ParagraphStyle(
            "SeverityValue",
            parent=cell_value_style,
            fontName="Helvetica-Bold",
            textColor=sev_color,
        )

        table_data = [
            [
                Paragraph("Incident Timestamp:", cell_label_style),
                Paragraph(timestamp, cell_value_style),
                Paragraph("Detected Class:", cell_label_style),
                Paragraph(detection_class, cell_value_style),
            ],
            [
                Paragraph("Alert Severity:", cell_label_style),
                Paragraph(severity, sev_cell_style),
                Paragraph("Confidence Level:", cell_label_style),
                Paragraph(confidence_str, cell_value_style),
            ],
        ]

        # Widths: 540 pt total usable printable width (612 - 72)
        event_table = Table(table_data, colWidths=[120, 150, 120, 150])
        event_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8f9fa")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#cccccc")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ])
        )
        elements.append(event_table)
        elements.append(Spacer(1, 14))

        # 3. Snapshot image embedded
        if snapshot_image_path and os.path.isfile(snapshot_image_path):
            section_title = ParagraphStyle(
                "SectionTitle",
                parent=styles["Normal"],
                fontSize=11,
                leading=14,
                fontName="Helvetica-Bold",
                textColor=colors.HexColor("#333333"),
                spaceAfter=6,
            )
            elements.append(Paragraph("Visual Evidence (Annotated Capture):", section_title))

            # Maintain 16:9 ratio fitting within page width
            img_w = 480
            img_h = 270
            try:
                img = Image(snapshot_image_path, width=img_w, height=img_h)
                elements.append(img)
                elements.append(Spacer(1, 14))
            except Exception as img_err:
                print(f"[report_generator] Error loading snapshot image: {img_err!r}")

        elements.append(Spacer(1, 10))

        # 4. Footer
        footer_text = (
            "Generated by SIH26162 AI Detection System — prototype, not a certified safety system"
        )
        elements.append(Paragraph(footer_text, footer_style))

        # Build PDF
        doc.build(elements)
        return output_pdf_path

    except Exception as exc:
        print(f"[report_generator] PDF generation failed: {exc!r}")
        return None
